sudo: false

language: python

python:
  - 3.6

install:
  - apt-get install p7zip-full libfuzzy-dev libpulse-dev
  - pip install codecov

script:
  - coverage run stuff/test_doc.py

after_success:
  - codecov